### ISSUE TITLE
Automatic Build of Docs

### ISSUE THREAD

**Issue by prohde** [JulianLoewe/Validating_Models#5]
Similar to #4, it would be nice if the docs would be build automatically on release of a new version. Usually, I deploy the docs using the `gh-pages` branch. I have a script and workflow that build the new docs and push them to the gh-pages branch on release. The regular gh-pages-deploy action is then also only triggered per release and not for every single push to the main branch. Let me know if you need any help with this.

**Comment by JulianLoewe** [comment]
I think that is already configured: https://julianloewe.github.io/Validating_Models/html/index.html should be the latest version of the documentation.

**Comment by JulianLoewe** [comment]
I have created a github action, which creates as an artifact the documentation and pushes it to github pages, without the need for an extra branch.
