### ISSUE TITLE
[Bug] Constraint Decision Tree Visulization

### ISSUE THREAD

**Issue by prohde** [JulianLoewe/Validating_Models#9]
This issue is caused due to the fact of changing to ``dtreeviz>=2.0.0``.

The method ``validating_models.visualizations.decision_trees.dtreeviz()`` returns a ``DTreeVizConv`` object see Line 675.
https://github.com/JulianLoewe/Validating_Models/blob/32084b3f74b051dccd166d80846362699de937f0/validating_models/visualizations/decision_trees.py#L675

However, the implementation of ``DTreeVizConv`` is based on ``dtreeviz<2.0.0``.
https://github.com/JulianLoewe/Validating_Models/blob/32084b3f74b051dccd166d80846362699de937f0/validating_models/visualizations/graphviz_helper.py#L11-L13
The new ``__init__`` method takes an instance of ``dtreeviz.models.shadow_decision_tree.ShadowDecTree``.

[dtreeviz version 1.4.1](https://github.com/parrt/dtreeviz/blob/fb5e17512b24b7f247ad2ddecd5501399d19ae1b/dtreeviz/trees.py#L40-L43)
[dtreeviz version 2.2.1](https://github.com/parrt/dtreeviz/blob/683cd48db16fc030af9d67e4ffd50371ffae24ad/dtreeviz/trees.py#L33-L41)

Additionally, the methods ``svg()``, ``save_svg()``, and ``save()`` have been removed. The later is also used by ``DTreeVizConv``. Is there a way to update the remaining part of ``validating_models`` to ``dtreeviz>=2.0.0`` or should we return to ``dtreeviz==1.4.1``?

**Comment by JulianLoewe** [comment]
Don't see the point in updating. I don't think that this library would benefit from that. What are the new features that this library inherits from the new detreeviz version? However this might help, if you really want to update for what ever reason: https://github.com/parrt/dtreeviz/blob/683cd48db16fc030af9d67e4ffd50371ffae24ad/dtreeviz/utils.py#L233

**Comment by prohde** [comment]
Many thanks! Well, it makes the dependency management in other projects a little easier. I fixed it in 3b05ae0.
